# Generated by Django 3.2.15 on 2022-11-03 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0026_auto_20221101_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='XblockSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('usage_key', models.CharField(help_text='The key of the xblock whose text was used for skills extraction.', max_length=255, unique=True)),
                ('requires_verification', models.BooleanField(default=True, help_text='Indicates whether skills applied to this block requires verification from users')),
                ('auto_processed', models.BooleanField(default=False, help_text='Indicates whether the text from this block was already processed')),
            ],
            options={
                'verbose_name': 'Xblock Skills',
                'verbose_name_plural': 'Xblock Skills',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='XblockSkillThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('relevant_count', models.IntegerField(blank=True, help_text='Number of times learners verified this skill', null=True)),
                ('irrelevant_count', models.IntegerField(blank=True, help_text='Number of times learners ignored this skill', null=True)),
                ('verified', models.BooleanField(default=False, help_text='Indicates that this skill has been finalized for this block')),
                ('confidence', models.FloatField(help_text='The extraction confidence threshold used for the skills extraction.')),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Blacklist this xblock skill, useful to handle false positives.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.skill')),
                ('xblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.xblockskills')),
            ],
            options={
                'verbose_name': 'Tagged item',
                'verbose_name_plural': 'Tagged items',
                'ordering': ('created',),
                'unique_together': {('xblock', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='xblockskills',
            name='skills',
            field=models.ManyToManyField(help_text='The ID of the skill extracted for the xblock.', through='taxonomy.XblockSkillThrough', to='taxonomy.Skill'),
        ),
    ]
